home/urls.py
from django.urls import path
from . import views

urlpatterns = [
    path('',views.home,name="home"),
    path('about.html/',views.about,name="About Us"),
    path('brands.html/',views.brands,name="brands"),
    path('login.html/',views.loginpage,name="login"),
    path('logout.html/',views.logoutpage,name="logout"),
    path('Compare.html/',views.compare,name="compare"),
    path('Search.html/',views.search,name="search"),
    path('Comaprison.html/',views.comparison,name="comparison"),
    path('carDetails.html/<str:id>/',views.car_detail,name="car_detail"),
    #sinup:
    path('accounts/signup/',views.signup,name="signup"),


    #AJAX CAR CALLING:
    # path('carSelect/',views.ajax_car,name='AjaxCarSelect')

]

run/urls.py
from django.contrib import admin
from django.urls import path,include

urlpatterns = [
    path('admin/', admin.site.urls),
    path('',include('home.urls')),
    path('setting/',include('settings.urls')),
    path('accounts/',include('allauth.urls')),
]

settings/urls.py
from django.urls import path
from . import views

urlpatterns = [
    path('',views.settings,name="settings")
]

home/models.py
from email.policy import default
from random import choices
from unittest.util import _MAX_LENGTH
from django.db import models

#BRANDS:
class Brands(models.Model):
    name = models.CharField(max_length=50,null=False)
    description = models.CharField(max_length=100,null=False)
    origin = models.CharField(max_length=50,null=False)

    def __str__(self):
        return self.name
    class Meta:
        verbose_name_plural = 'Brands'

#CARS:
class Cars(models.Model):
    TransChoices = [('Manual','Manual'),
    ('Automatic','Automatic'),]
    FuelType = [('Petrol','Petrol'),
    ('Diesel','Diesel'),
    ('Hybrid','Hybrid'),
    ('Electric','Electric'),

    ]
    SegmentType = [('Sedan','Sedan'),('SUV','SUV'),('Hatchback','Hatchback'),('MPV','MPV')]

    brand = models.ForeignKey(Brands,on_delete=models.CASCADE,null=True)
    segement = models.CharField(choices=SegmentType,max_length=20,null=False,default='Sedan')
    name = models.CharField(max_length=50,null=False)
    price = models.CharField(max_length=10,null=False)
    year =  models.IntegerField(null=False)
    engine = models.FloatField(null=False)
    transmission = models.CharField(choices = TransChoices,max_length=20,null=False)
    mileage = models.FloatField(max_length=10,null=False)
    fueltype = models.CharField(choices=FuelType,max_length=20,null=False)
    fueltank = models.FloatField(max_length=10,null=False)
    length = models.IntegerField(null=False)
    width = models.IntegerField(null=False)

    def __str__(self):
        return self.name 
    class Meta:
        verbose_name_plural = 'Cars'


class Profile(models.Model):

    name = models.CharField(max_length=50,null=False)
    email = models.CharField(max_length=50,null=True)
    phone = models.CharField(max_length=50,null=True)
    password = models.CharField(max_length=50,null=False)

    def __str__(self):
        return self.name + ' '+self.email + ' '+self.phone

    class Meta:
        verbose_name_plural = 'Profile'



class Review(models.Model):

    name = models.CharField(max_length=50,null=False)
    description = models.CharField(max_length=50,null=False)
    rating = models.IntegerField(null=False)
    created_at = models.DateTimeField(auto_now_add=True,null=False)
    def __str__(self):
        return self.name

    class Meta:

        verbose_name_plural = 'Review'



class CarSearchHistory(models.Model):
    brandName = models.ForeignKey(Brands,on_delete=models.CASCADE)
    carName = models.ForeignKey(Cars,on_delete=models.CASCADE)
    timeSearch = models.DateTimeField(auto_now_add=True)

settings/models.py
from django.db import models

# Create your models here.

home/forms.py
from django import forms
from .models import Cars,CarSearchHistory,Review

class Search(forms.ModelForm):
    class Meta:
        model = Cars
        fields = ['name','brand']

class DispReview(forms.ModelForm):
    class Meta:
        model = Review
        fields = '__all__'

class SearchHist(forms.ModelForm):
    class Meta:
        model = CarSearchHistory
        fields = '__all__'
    
    def __init__(self, *args, **kwargs):
        super().__init__(*args, **kwargs)

        self.fields['carName'].queryset = Cars.objects.none()

        if 'brandName' in self.data:
            cardId = self.data.get('brandName')
            self.fields['carName'].queryset = Cars.objects.filter(brand=cardId)

home/views.py
from multiprocessing import context
from unicodedata import name
from django.shortcuts import render,redirect
from django.http import HttpResponse
from .models import Brands,Cars,Review
from .forms import Search , SearchHist,DispReview
from django.contrib import messages      #for popup messages
from django.contrib.auth import login,logout,authenticate
from django.contrib.auth.models import User
from django.contrib.auth.decorators import login_required

from .models import Brands, Cars

# Create your views here.

def home(request):
    try:          
        data1 = Cars.objects.all()    
        data2 = Brands.objects.all()
        data3 = Review.objects.all()
        form = DispReview
        if request.method == 'POST':
            myData = DispReview(request.POST)
            if myData.is_valid():
                myData.save()
                messages.success(request,'Review added')
                return redirect('home')
        searchForm = SearchHist()
        context = {
        'Brands':data2,'Cars':data1, 'searchForm':searchForm,'review':data3}
    except Exception as e:
         context = {'Brands':'Data Not Found'}
    return render(request,'index.html',context)

def about(request):
    return render(request,'about.html')

def search(request):
    fetchBrand = request.GET['brand_name']
    fetchCar = request.GET['car_name']
    data = Cars.objects.filter(name=fetchCar)
    context = {'Cars':data}
    return render(request,'search.html',context)

@login_required(login_url='login')
def comparison(request):
    fetchBrand1 = request.GET['brand1']
    fetchBrand2 = request.GET['brand2']
    fetchCar1 = request.GET['car1']
    fetchCar2 = request.GET['car2']
    data1 = Cars.objects.filter(name=fetchCar1)
    data2 = Cars.objects.filter(name=fetchCar2)
    context = {'Car1':data1,'Car2':data2}
    return render(request,'comparison.html',context)

@login_required(login_url='login')
def brands(request):
    data = Brands.objects.all()
    context = {'brands':data}
    
    return render(request,'brands.html',context)

def loginpage(request):
    if request.method == 'POST':
        name = request.POST['username']
        password = request.POST['pass']
        user = authenticate(request,username=name,password=password)
        print(user)
        if user is not None:
            login(request,user)
            messages.success(request,'Logged in')
            return redirect('home')
        else:
            messages.warning(request,'Invalid credentials!!')
            return redirect('login')

    return render(request,'login.html')

def logoutpage(request):
    messages.success(request,'Logged out')
    logout(request)
    return render(request,'index.html')

def car_detail(request,id):
    data = Cars.objects.filter(brand=id)
    context = {'cars':data}
    return render(request,'car_detail.html',context)

@login_required(login_url='login')
def compare(request):
    try: 
        data1 = Brands.objects.all()         
        data2 = Cars.objects.all()    
        context = {'Cars':data2,'Brands':data1}
    except Exception as e:
         context = {'Cars':'Data Not Found'}
    return render(request,'compare.html',context)

#SIGNUP:
def signup(request):
    return render(request,'accounts/signup.html')



# def ajax_car(request):
#     b = request.GET['brandName']
#     carss = Cars.objects.filter(brand=b)
#     context = {'carss':carss}
#     return render(request,'ajaxcar.html',context)

settings/views.py
from django.shortcuts import render
from django.http import HttpResponse
# Create your views here.

def settings(request):
    return HttpResponse("Welcome to settings sir!!")

templates/about.html
{% extends 'common.html' %}

{% block content %}

    <!-- Page Header Start -->
    <div class="container-fluid page-header">
        <h1 class="display-3 text-uppercase text-white mb-3">About</h1>
        <div class="d-inline-flex text-white">
            <h6 class="text-uppercase m-0"><a class="text-white" href="">Home</a></h6>
            <h6 class="text-body m-0 px-3">/</h6>
            <h6 class="text-uppercase text-body m-0">About</h6>
        </div>
    </div>
    <!-- Page Header Start -->


    <!-- About Start -->
    <div class="container-fluid py-5">
        <div class="container pt-5 pb-3">
            <h1 class="display-4 text-uppercase text-center mb-5">Welcome To <span class="text-primary">CarEx</span></h1>
            <div class="row justify-content-center">
                <div class="col-lg-10 text-center">
                    <img class="w-75 mb-4" src="img/about.png" alt="">
                    <p>A website where the you can explore various cars
                        according to your requirements. Confused between cars? Well we provide you with a platform where you can
                        compare between cars with respect to their specifications which would
                        help you to consider all options and select the right car for you.
                        login/sign-up to your account.</p>
                        <hr class="mt-1 mx-1">
                        <p class="text-secondary">You can also sign-in via your google account.</p>
                </div>
            </div>
            <div class="row mt-3">
                <div class="col-lg-4 mb-2">
                    <div class="d-flex align-items-center bg-light p-4 mb-4" style="height: 150px;">
                        <div class="d-flex align-items-center justify-content-center flex-shrink-0 bg-primary ml-n4 mr-4" style="width: 100px; height: 100px;">
                            <i class="fa fa-2x fa-headset text-secondary"></i>
                        </div>
                        <h4 class="text-uppercase m-0">Latest Car Updates</h4>
                    </div>
                </div>
                <div class="col-lg-4 mb-2">
                    <div class="d-flex align-items-center bg-secondary p-4 mb-4" style="height: 150px;">
                        <div class="d-flex align-items-center justify-content-center flex-shrink-0 bg-primary ml-n4 mr-4" style="width: 100px; height: 100px;">
                            <i class="fa fa-2x fa-car text-secondary"></i>
                        </div>
                        <h4 class="text-light text-uppercase m-0">Car Comparison</h4>
                    </div>
                </div>
                <div class="col-lg-4 mb-2">
                    <div class="d-flex align-items-center bg-light p-4 mb-4" style="height: 150px;">
                        <div class="d-flex align-items-center justify-content-center flex-shrink-0 bg-primary ml-n4 mr-4" style="width: 100px; height: 100px;">
                            <i class="fa fa-2x fa-map-marker-alt text-secondary"></i>
                        </div>
                        <h4 class="text-uppercase m-0">Wide range of options</h4>
                    </div>
                </div>
            </div>
        </div>
    </div>
    <!-- About End -->



    {% endblock %}

templates/accounts/signup.html
{% extends 'templates/common.html' %}
{% load socialaccount %}
{% providers_media_js %}
{% load static %}
{% block content %}

<main class="page projects-page">
    <section class="vh-100 gradient-custom">
        <div class="container py-5 h-100">
          <div class="row d-flex justify-content-center align-items-center h-100">
            <div class="col-12 col-md-8 col-lg-6 col-xl-5">
              <div class="card bg-dark text-white" style="border-radius: 1rem;">
                <div class="card-body p-5 text-center">
                    <form class="signup" id="signup_form" method="post" action="/accounts/signup/">
                        <h1 class="fw-bold mb-2 text-uppercase">SIGN UP</h1>
                        <input type="hidden" name="csrfmiddlewaretoken" value="rrEedGVkqrmvXXMtSyqvoaJ7jAJqkjWShDeTsGhfFBhacAp2AMtjivJ5xU9hJWSr">
                        <div class="form-outline form-white mb-4">
                            <label for="id_username">Username:</label>
                          <input type="text" class="form-control form-control-lg" name="username"  autocomplete="username" minlength="1" maxlength="150" required="" id="id_username"> 
                        </div>
                        <p>
                          <label for="id_email">E-mail (optional):</label>
                          <input type="email" class="form-control form-control-lg" name="email" autocomplete="email" id="id_email">
                        </p>
                        <p>
                          <label for="id_password1">Password:</label>
                          <input type="password" class="form-control form-control-lg" name="password1" autocomplete="new-password" required="" id="id_password1">
                        </p>
                        <p>
                          <label for="id_password2">Password (again):</label>
                          <input type="password" class="form-control form-control-lg" name="password2"  autocomplete="new-password" required="" id="id_password2">  
                        </p>
                        
                        <button class="btn btn-outline-light btn-lg px-5" type="submit">Sign Up »</button>
                      </form>

      
                </div>
              </div>
            </div>
          </div>
        </div>
      </section>

</main>

    {% endblock %}



templates/ajaxcar.html
<option value="">--select Car--</option>

{% for car in carss %}

<option value="{{ car.pk }}">{{car.name}}</option>

{% endfor %}

templates/brands.html
{% extends 'common.html' %}

{% block content %}
    <!-- Page Header Start -->
    <div class="container-fluid page-header">
        <h1 class="display-3 text-uppercase text-white mb-3">Brands</h1>
        <div class="d-inline-flex text-white">
            <h6 class="text-uppercase m-0"><a class="text-white" href="">Home</a></h6>
            <h6 class="text-body m-0 px-3">/</h6>
            <h6 class="text-uppercase text-body m-0">Brands</h6>
        </div>
    </div>
    <!-- Page Header Start -->
    

    <!-- Services Start -->
    <div class="container-fluid py-5">
        <div class="container pt-5 pb-3">
            <h1 class="display-4 text-uppercase text-center mb-5">Brands</h1>
            <div class="row">
                {% for i in brands %}
                <div class="col-lg-4 col-md-4 mb-2"><a href="{% url 'car_detail' i.id %}"><button type="submit">
                    <div class="service-item d-flex flex-column justify-content-center px-4 mb-4">
                        <div class="d-flex align-items-center justify-content-between mb-3">
                            <div class="d-flex align-items-center justify-content-center ml-n4" style="width: 80px; height: 80px;">
                                <i class="fa fa-2x fa-taxi text-secondary"></i>
                            </div>
                        </div>
                        <h4 class="text-uppercase mb-3 text-primary">{{i.name}}</h4>
                        <p class="m-0">{{i.description}}</p>
                        <hr class="mt-1 mx-1">
                        <hr class="mt-1 mx-1">
                        <p class="m-0 text-center">Click to Explore Cars</p>
                    </div>
                    </button>
                </a> 
                </div>
                {% endfor %}
            </div>
        </div>
    </div>
    <!-- Services End -->
    {% endblock %}

templates/car_detail.html
{% extends './common.html' %}
{% load static %}

{% block content %}


<div class="container-fluid pt-5">
    <!-- {% for i in cars %}
    <h1 class="display-4 text-uppercase text-center mb-5"><span class="text-primary">{{i.brand}}</span></h1>
    {% endfor %} -->
    {% for i in cars %}
    <div class="container pt-5 pb-3 my-3 bg-dark text-white">
        <h1 class="display-4 text-uppercase mb-5 text-white">{{i.name}}</h1>
        <div class="row align-items-center pb-2">
            <div class="col-lg-6 mb-4">
                <img class="img-fluid" src="img/bg-banner.jpg" alt="">
            </div>
            <div class="col-lg-6 mb-4">
                <h4 class="mb-2 text-white">Price: {{i.price}} Lacs</h4>
                <div class="d-flex mb-3">
                    <h6 class="mr-2 text-white">Segment: {{i.segement}}</h6>
                </div>
                <p>{{i.year}}</p>
            </div>
        </div>
        <div class="row mt-n3 mt-lg-0 pb-4">
            <div class="col-md-3 col-6 mb-2">
                <i class="fa fa-car text-primary mr-2"></i>
                <span>Engine: {{i.engine}} litre</span>
            </div>
            <div class="col-md-3 col-6 mb-2">
                <i class="fa fa-cogs text-primary mr-2"></i>
                <span>Transmission: {{i.transmission}}</span>
            </div>
            <div class="col-md-3 col-6 mb-2">
                <i class="fa fa-car text-primary mr-2"></i>
                <span>Mileage: {{i.mileage}}km/l</span>
            </div>
            <div class="col-md-3 col-6 mb-2">
                <i class="fa fa-eye text-primary mr-2"></i>
                <span>Fuel Type: {{i.fueltype}}</span>
            </div>
            <div class="col-md-3 col-6 mb-2">
                <i class="fa fa-car text-primary mr-2"></i>
                <span>Fuel Capacity: {{i.fueltank}}litres</span>
            </div>
            <div class="col-md-3 col-6 mb-2">
                <i class="fa fa-road text-primary mr-2"></i>
                <span>Length: {{i.length}}mm</span>
            </div>
            <div class="col-md-3 col-6 mb-2">
                <i class="fa fa-road text-primary mr-2"></i>
                <span>Width: {{i.width}}mm</span>
            </div>
        </div>
    </div>
    {% endfor %}
</div>


{% endblock %}

templates/index.html
{% extends 'common.html' %}
{% load static %}
<!-- user account details -->
{% load account %}   
<!-- user specific details    -->
{% load socialaccount %}

{% block content %}

<!-- Search Start -->
<form action="{% url 'search' %}">
    <div class="container-fluid bg-white pt-3 px-lg-5">
        <div class="row mx-n2">
            <div class="col-xl-2 col-lg-4 col-md-6 px-2">
                <select class="custom-select px-4 mb-3" style="height: 50px;" name="brand_name" id="bname">
                    <option selected >Brand</option>
                    {% for i in Brands %}
                    <option value="{{i.name}}">{{i.name}}</option>
                    {% endfor %}
                </select>

                <!-- {{searchForm.as_p}} -->

            </div>
            <p class="output" id="output1"></p>
             <div class="col-xl-2 col-lg-4 col-md-6 px-2">
                <select class="custom-select px-4 mb-3" style="height: 50px;" name="car_name" id="particularCar">
                    <option selected>Select A Car</option>
                    {% for j in Cars %}
                        <option value="{{j.name}}">{{j.name}}</option>
                    {% endfor %}
                </select>
                
            </div>
            <div class="col-xl-2 col-lg-4 col-md-6 px-2">
                    <button class="btn btn-primary btn-block mb-3" type="submit" style="height: 50px;">Search</button>
            </div>
        </div>
    </div>
</form>
<hr class="mt-1 mx-1">
<!-- Search End -->


<!-- Carousel Start -->
<div class="container-fluid p-0" style="margin-bottom: 50px;">
    <div id="header-carousel" class="carousel slide" data-ride="carousel">
        <div class="carousel-inner">
            <div class="carousel-item active">
                <img class="w-100" src="{% static 'img/carousel-1.jpg' %}" alt="Image">
                <div class="carousel-caption d-flex flex-column align-items-center justify-content-center">
                    <div class="p-3" style="max-width: 900px;">
                        <h4 class="text-white text-uppercase mb-md-3">Best car for you</h4>
                        <h1 class="display-1 text-white mb-md-4">Select a car according to your requirements</h1>
                    </div>
                </div>
            </div>
            <div class="carousel-item">
                <img class="w-100" src="{% static 'img/carousel-2.jpg' %}" alt="Image">
                <div class="carousel-caption d-flex flex-column align-items-center justify-content-center">
                    <div class="p-3" style="max-width: 900px;">
                        <h4 class="text-white text-uppercase mb-md-3">Compare Cars</h4>
                        <h1 class="display-1 text-white mb-md-4">Car Comparison feature</h1>
                        <a href="{% url 'compare' %}" class="btn btn-primary py-md-3 px-md-5 mt-2">Compare</a>
                    </div>
                </div>
            </div>
        </div>
        <a class="carousel-control-prev" href="#header-carousel" data-slide="prev">
            <div class="btn btn-dark" style="width: 45px; height: 45px;">
                <span class="carousel-control-prev-icon mb-n2"></span>
            </div>
        </a>
        <a class="carousel-control-next" href="#header-carousel" data-slide="next">
            <div class="btn btn-dark" style="width: 45px; height: 45px;">
                <span class="carousel-control-next-icon mb-n2"></span>
            </div>
        </a>
    </div>
</div>
<!-- Carousel End -->

<hr class="mt-1 mx-1">
<div class="container-fluid py-5">
    <div class="container pt-5 pb-3">
        <h1 class="display-4 text-uppercase text-center mb-5">Welcome To <span class="text-primary">CarEx</span></h1>
        <div class="row justify-content-center">
            <div class="col-lg-10 text-center">
                <img class="w-75 mb-4" src="img/about.png" alt="">
                <p>A website where the you can explore various cars
                    according to your requirements. Confused between cars? Well we provide you with a platform where you can
                    compare between cars with respect to their specifications which would
                    help you to consider all options and select the right car for you.You can login/signup to your account.</p>
                    <hr class="mt-1 mx-1">
                    <p class="text-secondary">You can also sign-in via your google account.</p>
            </div>
        </div>
        <div class="row mt-3">
            <div class="col-lg-4 mb-2">
                <div class="d-flex align-items-center bg-light p-4 mb-4" style="height: 150px;">
                    <div class="d-flex align-items-center justify-content-center flex-shrink-0 bg-primary ml-n4 mr-4" style="width: 100px; height: 100px;">
                        <i class="fa fa-2x fa-headset text-secondary"></i>
                    </div>
                    <h4 class="text-uppercase m-0">Latest Car Updates</h4>
                </div>
            </div>
            <div class="col-lg-4 mb-2">
                <div class="d-flex align-items-center bg-secondary p-4 mb-4" style="height: 150px;">
                    <div class="d-flex align-items-center justify-content-center flex-shrink-0 bg-primary ml-n4 mr-4" style="width: 100px; height: 100px;">
                        <i class="fa fa-2x fa-car text-secondary"></i>
                    </div>
                    <h4 class="text-light text-uppercase m-0">Car Comparison</h4>
                </div>
            </div>
            <div class="col-lg-4 mb-2">
                <div class="d-flex align-items-center bg-light p-4 mb-4" style="height: 150px;">
                    <div class="d-flex align-items-center justify-content-center flex-shrink-0 bg-primary ml-n4 mr-4" style="width: 100px; height: 100px;">
                        <i class="fa fa-2x fa-map-marker-alt text-secondary"></i>
                    </div>
                    <h4 class="text-uppercase m-0">Wide range of options</h4>
                </div>
            </div>
        </div>
    </div>
</div>
<hr class="mt-1 mx-1">


<div class="container-fluid py-5">
    <div class="container pt-5 pb-3">
        <h1 class="display-4 text-uppercase text-center mb-5">CARS</h1>
        <div class="row">
            {% for i in Cars %}
            <div class="col-lg-4 col-md-4 mb-2">
                <div class="service-item d-flex flex-column justify-content-center px-4 mb-4">
                    <div class="d-flex align-items-center justify-content-between mb-3">
                        <div class="d-flex align-items-center justify-content-center ml-n4" style="width: 80px; height: 80px;">
                            <i class="fa fa-2x fa-taxi text-secondary"></i>
                        </div>
                    </div>
                    <h4 class="text-uppercase mb-3 text-primary">{{i.brand}} : {{i.name}}</h4>
                    <p class="text-uppercase mb-3 text-primary">{{i.segement}}</p>
                    <h4 class="text-uppercase mb-3 text-secondary">Price : {{i.price}}Lacs</h4>
                </div>
                </button>
            </a> 
            </div>
            {% endfor %}
        </div>
    </div>
</div>
<hr class="mt-1 mx-1">



<!-- Show Reviews -->
<h2 class="display-4 text-uppercase text-center mb-5">Reviews</h2>
<div class="row row-cols-1 row-cols-md-3 g-4">
    {% for i in review %}
    <div class="col">
      <div class="card h-100">
        <img src="https://mdbcdn.b-cdn.net/img/new/standard/city/044.webp" class="card-img-top" alt="Skyscrapers"/>
        <div class="card-body">
          <h5 class="card-title">{{i.name}}</h5>
          <p class="card-text">
            {{i.description}}
          </p>
          <p class="card-text">
            Rating :{{i.rating}}/10
          </p>
        </div>
        <div class="card-footer">
          <small class="text-muted">{{i.created_at}}</small>
        </div>
      </div>
    </div>
    {% endfor %}
  </div>

<!-- Contact Start -->
<hr class="mt-1 mx-1">
    
<div class="container-fluid py-4">
    <div class="container pt-5 pb-3">
        <h2 class="display-4 text-uppercase text-center mb-5">Write your review</h2>
        <div class="row">
            <div class="col-lg-7 mb-2 align-items-center justify-content-center">
                <div class="contact-form bg-secondary mb-4" style="padding: 30px;">
                    <form action = "" method="post">
                        {% csrf_token %}
                        <div class="row">
                            <div class="col-6 form-group">
                                <input type="text" class="form-control p-4" placeholder="Your Name" required="required">
                            </div>
                            <div class="col-6 form-group">
                                <input type="number" class="form-control p-4" placeholder="Rate this website"
                                    required="required">
                            </div>
                        </div>
                        <div class="form-group">
                            <textarea class="form-control py-3 px-4" rows="5" placeholder="Review"
                                required="required"></textarea>
                        </div>
                        <div>
                            <button class="btn btn-primary py-3 px-5" type="submit">Submit Review</button>
                        </div>

                    </form>
                      
                </div>
            </div>
        </div>
    </div>
</div>


<!-- Contact End -->



<!-- Vendor Start -->
<div class="container-fluid py-5">
    <div class="container py-5">
        <div class="owl-carousel vendor-carousel">
            <div class="bg-light p-4">
                <img src="img/vendor-1.png" alt="">
            </div>
            <div class="bg-light p-4">
                <img src="img/vendor-2.png" alt="">
            </div>
            <div class="bg-light p-4">
                <img src="img/vendor-3.png" alt="">
            </div>
            <div class="bg-light p-4">
                <img src="img/vendor-4.png" alt="">
            </div>
            <div class="bg-light p-4">
                <img src="img/vendor-5.png" alt="">
            </div>
            <div class="bg-light p-4">
                <img src="img/vendor-6.png" alt="">
            </div>
            <div class="bg-light p-4">
                <img src="img/vendor-7.png" alt="">
            </div>
            <div class="bg-light p-4">
                <img src="img/vendor-8.png" alt="">
            </div>
        </div>
    </div>
</div>
<!-- Vendor End -->

<script>
    // const out = document.getElementById('output1')
    // var text = brand_select.options[brand_select.selectedIndex].text

    // function bfunc(event){
    //     out.innerHTML = this.options[this.selectedIndex].text
    // }

    // $("#id_brandName").change(function () {
    //     let brandcar = $("#BrandForm").attr("data_brandCar");
    //     let brandname = $(this).val();
    //     console.log(brandcar);
    //     console.log(brandname);
    //     $.ajax({
    //         url: brandcar,
    //         data: {
    //             "brandName": brandname
    //         },
    //         success: function (data) {
    //             $('#particularCar').html(data)
    //         }
    //     })

    // })

</script>

{% endblock %}

templates/message.html
{% if messages %}
    {% for message in messages %}
        <div class="alert alert-{{message.tags}} m-2" id="msg" role="alert">
            {{message}}
    {% endfor %}
{% endif %}

        </div>